// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/just-a-developer-man/GO-route256/workshop-1/loms/internal/dto"

	mock "github.com/stretchr/testify/mock"

	models "github.com/just-a-developer-man/GO-route256/workshop-1/loms/internal/models"
)

// OrderManagementSystem is an autogenerated mock type for the OrderManagementSystem type
type OrderManagementSystem struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, userID, info
func (_m *OrderManagementSystem) CreateOrder(ctx context.Context, userID models.UserID, info dto.CreateOrderInfo) (models.OrderID, error) {
	ret := _m.Called(ctx, userID, info)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 models.OrderID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID, dto.CreateOrderInfo) (models.OrderID, error)); ok {
		return rf(ctx, userID, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID, dto.CreateOrderInfo) models.OrderID); ok {
		r0 = rf(ctx, userID, info)
	} else {
		r0 = ret.Get(0).(models.OrderID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID, dto.CreateOrderInfo) error); ok {
		r1 = rf(ctx, userID, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderByID provides a mock function with given fields: ctx, orderID
func (_m *OrderManagementSystem) OrderByID(ctx context.Context, orderID models.OrderID) (dto.OrderInfo, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for OrderByID")
	}

	var r0 dto.OrderInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID) (dto.OrderInfo, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID) dto.OrderInfo); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(dto.OrderInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OrderID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderManagementSystem creates a new instance of OrderManagementSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderManagementSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderManagementSystem {
	mock := &OrderManagementSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
